### ISSUE TITLE
Why the test result of KITTI only include car class？

### ISSUE THREAD

**Issue by zhangchuang-zc** [MedChaabane/DEFT#10]
HI! Thanks for your excellent work！
I run the test.py to get the KITTI result, but it only includes car class，not pedestrians and cyclist.
Does your code only focus the car class during training, or does it only detect the car class during testing? I don't find the corresponding code in the project, can you help me? @MedChaabane 
Thanks！

**Comment by MedChaabane** [comment]
Hi, Thanks for your interest in our work! In KITTI we just trained and tested our model on car class. in nuScenes dataset,  we have tested our model for tracking car, pedestrians, cyclist and also four other classes.
Thanks,

**Comment by zhangchuang-zc** [comment]
Thanks for your reply! How did you achieve only tracking car in the training and testing process？I found your model `model_kitti.pth` corresponds to three classes, but the testing results only include car class. I did not find the corresponding code in your project, can you help me find the corresponding code? I want to train a model that only tracks pedestrians, can you help me? @MedChaabane 
Thank you very much!

**Comment by MedChaabane** [comment]
Hi, in the tracker code (https://github.com/MedChaabane/DEFT/blob/main/src/lib/utils/tracker.py ) , line 793 we filter only car class for tracking, " if det["class"] == 2 " . You can change in that line to the class id of pedestrian instead of class id of car "2" and it should test on pedestrians. However, the kitti train data does not have enough data on pedestrian class so I don't expect that it will works well on pedestrians without pre-training it on other pedestrian datasets first.

**Comment by zhangchuang-zc** [comment]
Thanks for your help! @MedChaabane
